export const ADD_ROOMS = 'ADD_ROOMS';
export const ROOMS_FAILED = 'ROOMS_FAILED';
export const POST_ROOMS = 'POST_ROOMS';

export const APARTMENTS_LOADING = 'APARTMENTS_LOADING';
export const APARTMENTS_FAILED = 'APARTMENTS_FAILED';
export const ADD_APARTMENTS = 'ADD_APARTMENTS';
export const DELETE_APARTMENT = 'DELETE_APARTMENTS';
export const POST_APARTMENT = 'POST_APARTMENTS';


export const USERS_LOADING = 'USERS_LOADING';
export const ADD_USERS = 'ADD_USERS';
export const USERS_FAILED = 'USERS_FAILED';
export const POST_USER = 'POST_USER';

export const APARTMENTTYPE_LOADING = 'APARTMENTTYPE_LOADING';
export const APARTMENTTYPE_FAILED = 'APARTMENTTYPE_FAILED';
export const ADD_APARTMENTTYPE = 'ADD_APARTMENTTYPE';

export const EQUIPMENTTYPE_LOADING = 'EQUIPMENTTYPE_LOADING';
export const EQUIPMENTTYPE_FAILED = 'EQUIPMENTTYPE_FAILED';
export const ADD_EQUIPMENTTYPE = 'ADD_EQUIPMENTTYPE';

export const ROOMTYPE_LOADING = 'ROOMTYPE_LOADING';
export const ROOMTYPE_FAILED = 'ROOMTYPE_FAILED';
export const ADD_ROOMTYPE = 'ADD_ROOMTYPE';


export const EQUIPMENT_LOADING = 'EQUIPMENT_LOADING';
export const EQUIPMENT_FAILED = 'EQUIPMENT_FAILED';
export const ADD_EQUIPMENT = 'ADD_EQUIPMENT'; 
export const UPDATE_EQUIPMENT= 'UPDATE_EQUIPMENT';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';